#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/trundle/jupyter/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/trundle/jupyter/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/trundle/Projects/NST-variation/CA3_pyramidal_neuron/model_files/x86_64/.libs/libnrnmech.so" "$@"
